# Generated by Django 4.2.5 on 2023-10-04 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_create_wss_login_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actions", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "transaction_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("symbol", models.CharField(blank=True, max_length=100, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "price_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "fee",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("date_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wss_login",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.wsslogin"),
                ),
            ],
        ),
    ]
