# Generated by Django 4.2.5 on 2023-10-04 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_timezone_on_transaction"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={
                (
                    "wss_login",
                    "transaction_type",
                    "symbol",
                    "quantity",
                    "type",
                    "price_status",
                    "fee",
                    "date_time",
                )
            },
        ),
    ]
